releases/20201022085319/config/routes.rb
Rails.application.routes.draw do
  get 'home/top'
  get '/search', to: 'search#search'
  get 'charts/monthly'
  get '/events', to: 'events#index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    # 退会機能
    member do
      get "unsubscribe"
      patch "withdraw"
      get "following"
      get "follower"
    end
  end

  root to: 'home#top'
end

releases/20201022085319/app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  before_action :authenticate_user!

  def monthly
    # pre_previewのパラメータが入っていれば、1ヶ月"前"を@target_monthに入れる
    if params[:pre_preview].present?
      @target_month = Date.parse(params[:pre_preview]) << 1
    # next_previewのパラメータが入っていれば、1ヶ月"後"を@target_monthに入れる
    elsif params[:next_preview].present?
      @target_month = Date.parse(params[:next_preview]) >> 1
    # それ以外は、現在の日付を@target_monthに入れる
    else
      @target_month = Time.current.to_date
    end

    # current_userがフォローしているユーザー＝follower_idがcurrent_userであるユーザー
    # pluckでfollowed_id（フォローしているユーザーのID）を配列する
    # pushでフォローしているユーザーに加えて、自分の情報も表示させる
    target_user = Relationship.where(follower_id: current_user.id).pluck(:followed_id).push(current_user.id)

    # joinsメソッドでusersテーブルとpostsテーブルを 内部結合する
    # whereメソッドで1ヶ月のデータと退会していないユーザーを絞り込む
    # groupメソッドでユーザーごとにレコードをまとめる
    # orderメソッドで歩数（steps）の多い順にユーザーを並び替える
    @users = User.joins(:posts).
      where(id: target_user).
      where(posts: { created_at: @target_month.all_month }).
      where(users: { is_deleted: false }).
      group(:id).order("sum(posts.steps) desc")
  end
end

releases/20201022085319/app/helpers/charts_helper.rb
module ChartsHelper
end

releases/20201022085319/app/views/charts/monthly.html.erb
<div class="container">
  <div class="row">
    <div class="text-center">
      <h2 class="col-xs-12 chart-heading">
        <%= link_to "", charts_monthly_path(:pre_preview => @target_month), class: "glyphicon glyphicon-chevron-left" %>
        <%= "#{@target_month.year}年#{@target_month.month}月のランキング" %>
        <%= link_to "", charts_monthly_path(:next_preview => @target_month), class: "glyphicon glyphicon-chevron-right" %>
      </h2>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <table class="table table-hover table-bordered text-center ranking-table">
        <thead class="thead-light">
          <tr>
            <th class="text-center">順位</th>
            <th class="text-center">ユーザー名</th>
            <th class="text-center">合計(歩)</th>
          </tr>
        </thead>
        <tbody>
         <% @users.each_with_index do |user,i| %>
            <tr>
              <td class="text-center" style="vertical-align: middle;">
                <%= i += 1 %>
              </td>
              <div class="form-inline">
                <td>
                  <%= link_to(user_path(user)) do %>
                    <%= attachment_image_tag(user, :profile_image, size: "50x50", fallback: "no_image.png", style: "border-radius: 50%;") %>
                    <p class="rankng-user"><%= user.name %></p>
                  <% end %>
                </td>
              </div>
              <td style="vertical-align: middle;">
                <%= user.posts.where(created_at: Time.now.all_month).sum(:steps) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>