releases/20201024080614/config/routes.rb
Rails.application.routes.draw do
  get 'home/top'
  get '/search', to: 'search#search'
  get 'charts/monthly'
  get '/events', to: 'events#index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    # 退会機能
    member do
      get "unsubscribe"
      patch "withdraw"
      get "following"
      get "follower"
    end
  end

  root to: 'home#top'
end

releases/20201024080614/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

releases/20201024080614/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :comment, presence: true
end

releases/20201024080614/app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

releases/20201024080614/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  attachment :image

  validates :title, presence: true
  validates :body, presence: true
  validates :steps, presence: true, numericality: { only_integer: true, greater_than: 0 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

releases/20201024080614/app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

releases/20201024080614/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  # Relationshipモデルのfollower_idにuser_idを格納する
  has_many :follower, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :followed, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  attachment :profile_image

  validates :name, presence: true
  validates :uid, presence: true, length: { in: 2..20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
  validates :target_number, numericality: { only_integer: true, greater_than: 0 }, allow_blank: true

  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーをアンフォローする
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしているかを確認する
  def following?(user)
    following_user.include?(user)
  end

  # is_deletedがfalseの場合（有効会員）、ログイン可能
  def active_for_authentication?
    super && (is_deleted == false)
  end
end

releases/20201024080614/app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  before_action :authenticate_user!

  def monthly
    # pre_previewのパラメータが入っていれば、1ヶ月"前"を@target_monthに入れる
    if params[:pre_preview].present?
      @target_month = Date.parse(params[:pre_preview]) << 1
    # next_previewのパラメータが入っていれば、1ヶ月"後"を@target_monthに入れる
    elsif params[:next_preview].present?
      @target_month = Date.parse(params[:next_preview]) >> 1
    # それ以外は、現在の日付を@target_monthに入れる
    else
      @target_month = Time.current.to_date
    end

    # current_userがフォローしているユーザー＝follower_idがcurrent_userであるユーザー
    # pluckでfollowed_id（フォローしているユーザーのID）を配列する
    # pushでフォローしているユーザーに加えて、自分の情報も表示させる
    target_user = Relationship.where(follower_id: current_user.id).pluck(:followed_id).push(current_user.id)

    # joinsメソッドでusersテーブルとpostsテーブルを 内部結合する
    # whereメソッドで1ヶ月のデータと退会していないユーザーを絞り込む
    # groupメソッドでユーザーごとにレコードをまとめる
    # orderメソッドで歩数（steps）の多い順にユーザーを並び替える
    @users = User.joins(:posts).
      where(id: target_user).
      where(posts: { created_at: @target_month.all_month }).
      where(users: { is_deleted: false }).
      group(:id).order("sum(posts.steps) desc")
  end
end

releases/20201024080614/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

releases/20201024080614/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to posts_path, notice: "記録に成功しました！"
    else
      render "new"
    end
  end

  def index
    # ユーザーごとに投稿一覧を表示させる
    if params["user"]
      @user = User.find(params["user"])
      @posts = @user.posts.all.order(created_at: :desc).page(params[:page]).per(6)
    else
      @user = current_user
      @posts = @user.posts.all.order(created_at: :desc).page(params[:page]).per(6)
    end
    # 退会ユーザーの投稿ページは表示しない
    if @user.is_deleted == true
      redirect_to posts_path
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.order(created_at: :desc)
  end

  def edit
    @post = Post.find(params[:id])
    @user = User.find_by(id: @post.user_id)
    if @post.user == current_user
      render "edit"
    else
      redirect_to posts_path
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post), notice: "更新に成功しました！"
    else
      render "edit"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path, notice: "削除に成功しました！"
  end

  private

  def post_params
    params.require(:post).permit(:steps, :image, :title, :body)
  end
end

releases/20201024080614/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update, :unsubscribe, :withdraw]

  def show
    @user = User.find(params[:id])
    @followings = @user.following_user.where(is_deleted: false)
    @followers = @user.follower_user.where(is_deleted: false)

    # 退会ユーザーの情報は表示しない
    if @user.is_deleted == true
      redirect_to user_path(current_user)
    end

    # 目標達成率 (to_fで型を小数にすることで計算を可能にする。)
    posts = Post.all
    achievement = current_user.posts.where(created_at: Time.now.all_week).sum(:steps)
    if !current_user.target_number.nil?
      @achievement_rate = (achievement.to_f / current_user.target_number.to_f * 100).round
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "更新に成功しました！"
    else
      render "edit"
    end
  end

  # 退会処理
  def unsubscribe
    @user = User.find(params[:id])
  end

  def withdraw
    @user = User.find(params[:id])
    if @user.update(is_deleted: true)
      sign_out current_user
    end
    redirect_to root_path, notice: "退会処理が完了しました！"
  end

  # ユーザーIDの検索結果を表示
  def search
    @users = User.all
  end

  # 自分がフォローしているユーザー一覧
  def following
    @user = User.find(params[:id])
    @followings = @user.following_user.where(is_deleted: false)
  end

  # 自分をフォローしているユーザー一覧
  def follower
    @user = User.find(params[:id])
    @followers = @user.follower_user.where(is_deleted: false)
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image, :is_deleted, :uid, :email, :target_number)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

releases/20201024080614/app/helpers/application_helper.rb
module ApplicationHelper
end

releases/20201024080614/app/helpers/charts_helper.rb
module ChartsHelper
end

releases/20201024080614/app/helpers/comments_helper.rb
module CommentsHelper
end

releases/20201024080614/app/helpers/events_helper.rb
module EventsHelper
end

releases/20201024080614/app/helpers/favorites_helper.rb
module FavoritesHelper
end

releases/20201024080614/app/helpers/home_helper.rb
module HomeHelper
end

releases/20201024080614/app/helpers/posts_helper.rb
module PostsHelper
end

releases/20201024080614/app/helpers/relationships_helper.rb
module RelationshipsHelper
end

releases/20201024080614/app/helpers/search_helper.rb
module SearchHelper
end

releases/20201024080614/app/helpers/users_helper.rb
module UsersHelper
end

releases/20201024080614/app/views/layouts/_header.html.erb
<header>
  <div class="container">
    <nav class="nav navbar-nav navbar-left">
      <%= link_to root_path do %>
        <%= image_tag 'logo_silhouette.jpg' %>
        <%= image_tag 'logo.png' %>
      <% end %>
    </nav>

    <nav class="nav navbar-nav navbar-right">
      <div class="menu">
         <ul class="list-group list-group-horizontal">
             <% if user_signed_in? %>
              <li><span class="material-icons">account_circle</span><%= link_to 'マイページ',user_path(current_user) %></li>
              <li><span class="material-icons">add_photo_alternate</span><%= link_to '投稿する',new_post_path(current_user) %></li>
              <li><span class="material-icons">view_module</span><%= link_to '投稿一覧',posts_path %></li>
              <li><span class="material-icons">exit_to_app</span><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><span class="material-icons">how_to_reg</span><%= link_to '無料会員登録', new_user_registration_path,class: 'sign_up' %></li>
              <li><span class="material-icons">login</span><%= link_to 'ログイン', new_user_session_path ,class: 'sign_in'%></li>
            <% end %>
        </ul>
      </div>

      <!-- ハンバーガーメニュー -->
      <div class="hamburger">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </nav>

    <% if user_signed_in? %>
      <div class="search" >
        <%= form_tag(search_path, method: :get) do %>
          <%= text_field_tag 'search[content]', "", placeholder: 'ユーザーIDを入力' %>
          <%= button_tag type: 'submit' do %>
            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</header>

releases/20201024080614/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sampo Log</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&family=Noto+Sans+JP:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <%= favicon_link_tag 'favicon.png' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="wrapper">
      <p id="notice" class="col-xs-12 text-center"><%= notice %></p>
      <main>
          <%= yield %>
      </main>

      <footer>
        <p>© 2020 Sampo Log</p>
      </footer>
    </div>

    <!-- アニメーションスクリプト「AOS」 -->
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script>AOS.init();</script>
  </body>
</html>