releases/20201024081626/config/routes.rb
Rails.application.routes.draw do
  get 'home/top'
  get '/search', to: 'search#search'
  get 'charts/monthly'
  get '/events', to: 'events#index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    # 退会機能
    member do
      get "unsubscribe"
      patch "withdraw"
      get "following"
      get "follower"
    end
  end

  root to: 'home#top'
end

releases/20201024081626/app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

releases/20201024081626/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.new(post_id: @post.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.find_by(post_id: @post.id)
    favorite.destroy
    redirect_to request.referer
  end
end

releases/20201024081626/app/helpers/favorites_helper.rb
module FavoritesHelper
end

releases/20201024081626/app/views/favorites/_favorite-button.html.erb
<span id = "favorite-<%= post.id %>">
	<% if post.favorited_by?(current_user) %>
		<%= link_to post_favorites_path(post), method: :delete, data: {"turbolinks" => false}, remote: true do %>
	  		<span class="material-icons heart">favorite</span>
		<% end %>
	<% else %>
		<%= link_to post_favorites_path(post), method: :post, data: {"turbolinks" => false}, remote: true do %>
	 		<span class="material-icons heart-empty">favorite_border</span>
		<% end %>
	<% end %>
</span>

releases/20201024081626/app/views/favorites/create.js.erb
if (location.pathname == '/posts') {
  $("#favorite-<%= post.id %>").html("<%= j(render 'posts/favorite-button',  post: post ) %>")
} else {
  $("#favorite-<%= post.id %>").html("<%= j(render 'posts/favorite-button',  post: @post ) %>")
}

releases/20201024081626/app/views/favorites/destroy.js.erb
if (location.pathname == '/posts') {
  $("#favorite-<%= post.id %>").html("<%= j(render 'posts/favorite-button',  post: post ) %>")
} else {
  $("#favorite-<%= post.id %>").html("<%= j(render 'posts/favorite-button',  post: @post ) %>")
}