releases/20201025063045/config/routes.rb
Rails.application.routes.draw do
  get 'home/top'
  get '/search', to: 'search#search'
  get 'charts/monthly'
  get '/events', to: 'events#index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    # 退会機能
    member do
      get "unsubscribe"
      patch "withdraw"
      get "following"
      get "follower"
    end
  end

  root to: 'home#top'
end

releases/20201025063045/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :comment, presence: true
end

releases/20201025063045/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @comment = current_user.comments.new(comment_params)
    @comment.post_id = @post.id
    if @comment.save
      redirect_to request.referer, notice: "コメントを記録しました！"
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      redirect_to request.referer, notice: "コメントを削除しました！"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:comment, :post_id, :user_id)
  end
end

releases/20201025063045/app/helpers/comments_helper.rb
module CommentsHelper
end

releases/20201025063045/app/views/comments/_form.html.erb
<%= form_with(model:[post, comment], data: {remote: true}) do |f| %>
	<div class="col-xs-12">
		<span class="material-icons">add_comment</span></span><%= f.label :comment, "コメントする" %> <br>
		<%= f.text_area :comment, size: "90x5", class: "form-control", placeholder: "コメントを入力してください。"  %> <br>
	</div>

	<div class="col-xs-12 comment-submit">
		 <%= f.submit '送信', class: "btn btn-default col-xs-3" %>
	</div>
<% end %>

releases/20201025063045/app/views/comments/_index.html.erb
<div class="col-xs-12">
	<table class="table">
		<thead>
			<tr>
				<th style="padding-left: 0;">
					<span class="material-icons">comment</span><%= label :comment, "コメント一覧" %>
				</th>
			</tr>
		</thead>
		<% comments.each do |comment| %>
			<tbody>
				<tr>
					<td class="col-xs-4">
						<%= link_to user_path(comment.user), class: "user_#{comment.user.id}" do %>
							<%= attachment_image_tag comment.user, :profile_image, size: "50x50",  fallback: "no_image.png", style: "border-radius: 50%;" %>
							<p class="comment-user-name"><%= comment.user.name %></p>
						<% end %>
						<% if comment.user.is_deleted == true %>
							<span>（退会済み）</span>
						<% end %>
					</td>
					<td>
						<p><%= comment.comment %></p>
						(<%= I18n.l comment.created_at, format: :short %>)
					</td>
					<td>
						<% if comment.user == current_user %>
							<%= link_to '削除', post_comment_path(comment.post, comment), class: 'btn btn-danger col-xs-12', method: :delete, remote: true %>
						<% end %>
					</td>
				</tr>
			</tbody>
		<% end %>
	</table>
</div>

releases/20201025063045/app/views/comments/create.js.erb
$(document).addEventListener('turbolinks:load', function() {
	$// コメント送信後のコメント入力フォームを空にする
	("textarea").val("");
	$("#comment-area").html("<%= j(render 'index', comments: @comments ) %>");
	$("#comment-form").html("<%= j(render 'form', comment: @comment, post: @post ) %>");
});

releases/20201025063045/app/views/comments/destroy.js.erb
$(document).addEventListener('turbolinks:load', function() {
	$("#comment-area").html("<%= j(render 'index', comments: @comments) %>");
});